<script lang="ts">
	import '../app.css';
	import { onMount } from 'svelte';
	import { base } from '$app/paths';

	let { children } = $props();

	onMount(() => {
		// Register the Workbox service worker generated by vite-plugin-pwa. We do
		// this explicitly (rather than relying on auto-injection) because the app
		// ships as a client-rendered SPA shell. It self-updates on new deploys
		// thanks to registerType: 'autoUpdate'.
		if (import.meta.env.PROD && 'serviceWorker' in navigator) {
			navigator.serviceWorker.register(`${base}/sw.js`).catch(() => {
				/* offline support unavailable — the app still works online */
			});
		}
	});
</script>

{@render children()}
